export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_REQUEST = 'SAVE_PROFILE_REQUEST';
export const SAVE_PROFILE_FAILURE = 'SAVE_PROFILE_FAILURE';

export const SAVE_PROFILE_AVATAR = 'SAVE_PROFILE_AVATAR';
export const SAVE_PROFILE_AVATAR_SUCCESS = 'SAVE_PROFILE_AVATAR_SUCCESS';
export const SAVE_PROFILE_AVATAR_REQUEST = 'SAVE_PROFILE_AVATAR_REQUEST';
export const SAVE_PROFILE_AVATAR_FAILURE = 'SAVE_PROFILE_AVATAR_FAILURE';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';

export const FETCH_GALLERY = 'FETCH_GALLERY';
export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
export const FETCH_GALLERY_REQUEST = 'FETCH_GALLERY_REQUEST';
export const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

export const FETCH_GALLERY_PHOTO = 'FETCH_GALLERY_PHOTO';
export const FETCH_GALLERY_PHOTO_SUCCESS = 'FETCH_GALLERY_PHOTO_SUCCESS';
export const FETCH_GALLERY_PHOTO_REQUEST = 'FETCH_GALLERY_PHOTO_REQUEST';
export const FETCH_GALLERY_PHOTO_FAILURE = 'FETCH_GALLERY_PHOTO_FAILURE';

export const SAVE_GALLERY_PHOTO = 'SAVE_GALLERY_PHOTO';
export const SAVE_GALLERY_PHOTO_SUCCESS = 'SAVE_GALLERY_PHOTO_SUCCESS';
export const SAVE_GALLERY_PHOTO_REQUEST = 'SAVE_GALLERY_PHOTO_REQUEST';
export const SAVE_GALLERY_PHOTO_FAILURE = 'SAVE_GALLERY_PHOTO_FAILURE';

export const DELETE_GALLERY_PHOTO = 'DELETE_GALLERY_PHOTO';
export const DELETE_GALLERY_PHOTO_SUCCESS = 'DELETE_GALLERY_PHOTO_SUCCESS';
export const DELETE_GALLERY_PHOTO_REQUEST = 'DELETE_GALLERY_PHOTO_REQUEST';
export const DELETE_GALLERY_PHOTO_FAILURE = 'DELETE_GALLERY_PHOTO_FAILURE';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST';
export const FETCH_CONVERSATIONS_FAILURE = 'FETCH_CONVERSATIONS_FAILURE';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export const FETCH_FEEDBACKS = 'FETCH_FEEDBACKS';
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS';
export const FETCH_FEEDBACKS_REQUEST = 'FETCH_FEEDBACKS_REQUEST';
export const FETCH_FEEDBACKS_FAILURE = 'FETCH_FEEDBACKS_FAILURE';

export const FETCH_MODELS = 'FETCH_MODELS';
export const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';
export const FETCH_MODELS_REQUEST = 'FETCH_MODELS_REQUEST';
export const FETCH_MODELS_FAILURE = 'FETCH_MODELS_FAILURE';

export const FETCH_PHOTOGRAPHERS = 'FETCH_PHOTOGRAPHERS';
export const FETCH_PHOTOGRAPHERS_SUCCESS = 'FETCH_PHOTOGRAPHERS_SUCCESS';
export const FETCH_PHOTOGRAPHERS_REQUEST = 'FETCH_PHOTOGRAPHERS_REQUEST';
export const FETCH_PHOTOGRAPHERS_FAILURE = 'FETCH_PHOTOGRAPHERS_FAILURE';

export const FETCH_MODEL = 'FETCH_MODEL';
export const FETCH_MODEL_SUCCESS = 'FETCH_MODEL_SUCCESS';
export const FETCH_MODEL_REQUEST = 'FETCH_MODEL_REQUEST';
export const FETCH_MODEL_FAILURE = 'FETCH_MODEL_FAILURE';

export const FETCH_PHOTOGRAPHER = 'FETCH_PHOTOGRAPHER';
export const FETCH_PHOTOGRAPHER_SUCCESS = 'FETCH_PHOTOGRAPHER_SUCCESS';
export const FETCH_PHOTOGRAPHER_REQUEST = 'FETCH_PHOTOGRAPHER_REQUEST';
export const FETCH_PHOTOGRAPHER_FAILURE = 'FETCH_PHOTOGRAPHER_FAILURE';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const LEAVE_FEEDBACK = 'LEAVE_FEEDBACK';
export const LEAVE_FEEDBACK_SUCCESS = 'LEAVE_FEEDBACK_SUCCESS';
export const LEAVE_FEEDBACK_REQUEST = 'LEAVE_FEEDBACK_REQUEST';
export const LEAVE_FEEDBACK_FAILURE = 'LEAVE_FEEDBACK_FAILURE';